#ifndef __PLATFROM_H
#define __PLATFROM_H

#include <stdint.h>
#include <imgdts.h>

#define readl(reg) (*((volatile unsigned int *) (reg)))
#define writel(reg, value) *((volatile unsigned int *) (reg)) = value

#define SUNXI_UART0_BA 0x02500000
#define SUNXI_UART3_BA 0x02500C00

#define UART_THR 0
#define UART_RHR 0
#define UART_DLL 0
#define UART_DLH 4
#define UART_IER 4
#define UART_IIR 8
#define UART_FCR 8
#define UART_LCR 0xc
#define UART_MCR 0x10
#define UART_LSR 0x14
#define UART_MSR 0x18
#define UART_USR 0x7C

#define LED_TOG                                                   \
    do {                                                          \
        if (readl(0x020000a0) & (1 << 22)) {                      \
            writel(0x020000a0, readl(0x020000a0) & (~(1 << 22))); \
        } else {                                                  \
            writel(0x020000a0, readl(0x020000a0) | ((1 << 22)));  \
        }                                                         \
    } while (0)

#define SUNXI_MSGBOX_ARM_BASE 0x03003000
#define SUNXI_MSGBOX_DSP_BASE 0x01701000

#define SUNXI_GPIO_BASE 0x2000000

#define SUNXI_CCU_BASE        0x02001000UL
#define SUNXI_DSP_CLK_REG     (SUNXI_CCU_BASE + 0x0C70)

#define SUNXI_HOSC_FREQ       24000000UL    // 24 MHz

/*
 * OpenCentauri: From the CC Linux Device Tree:
 * share_space@0x42100000 {
 *     compatible = "allwinner,sun8iw20p1-dsp-share-space";
 *     ...
 *     reg = <0x42100000 0x1000 0x42101000 0x1000 0x42102000 0xe000 0x00 0x00>;
 */
// Seems like correct base address for 8KB buf
#define SUNXI_SHAREDSPACE_BASE 0x42100000

#define TIMER1_IRQ 1
#define MSGBOX_IRQ 3

/*
 * two msgbox
 * msgbox 0  dsp->cpu  cpu read
 * msgbox 1  cpu->dsp  cpu write
 */

#define SUNXI_MSGBOX_MAX_CHANNEL 2
#define SUNXI_MSGBOX_MAX_QUEUE 8

#define SUNXI_MSGBOX_RD_IRQ_ENABLE_REG \
    (SUNXI_MSGBOX_DSP_BASE + 0x20 + (0) * 0x100)
#define SUNXI_MSGBOX_WR_IRQ_ENABLE_REG \
    (SUNXI_MSGBOX_DSP_BASE + 0x30 + (0) * 0x100)

#define SUNXI_MSGBOX_RD_IRQ_STATUS_REG \
    (SUNXI_MSGBOX_DSP_BASE + 0x24 + (0) * 0x100)
#define SUNXI_MSGBOX_WR_IRQ_STATUS_REG \
    (SUNXI_MSGBOX_DSP_BASE + 0x34 + (0) * 0x100)

#define SUNXI_MSGBOX_RD_IRQ_ENABLE(ch)     \
    writel(SUNXI_MSGBOX_RD_IRQ_ENABLE_REG, \
           readl(SUNXI_MSGBOX_RD_IRQ_ENABLE_REG) | (1 << (2 * (ch))))
#define SUNXI_MSGBOX_RD_IRQ_DISABLE(ch)    \
    writel(SUNXI_MSGBOX_RD_IRQ_ENABLE_REG, \
           readl(SUNXI_MSGBOX_RD_IRQ_ENABLE_REG) & (~(1 << (2 * (ch)))))

#define SUNXI_MSGBOX_RD_IRQ_IS_PENDING(ch) \
    (readl(SUNXI_MSGBOX_RD_IRQ_STATUS_REG) & (1 << (2 * (ch))))
#define SUNXI_MSGBOX_RD_IRQ_CLR_PENDING(ch) \
    writel(SUNXI_MSGBOX_RD_IRQ_STATUS_REG, (1 << (2 * (ch))))

#define SUNXI_MSGBOX_ARM_MSG_STATUS_REG(ch) \
    (SUNXI_MSGBOX_ARM_BASE + 0x60 + (0) * 0x100 + (ch) *0x4)
#define SUNXI_MSGBOX_DSP_MSG_STATUS_REG(ch) \
    (SUNXI_MSGBOX_DSP_BASE + 0x60 + (0) * 0x100 + (ch) *0x4)

#define SUNXI_MSGBOX_ARM_MSG_REG(ch) \
    (SUNXI_MSGBOX_ARM_BASE + 0x70 + (0) * 0x100 + (ch) *0x4)
#define SUNXI_MSGBOX_DSP_MSG_REG(ch) \
    (SUNXI_MSGBOX_DSP_BASE + 0x70 + (0) * 0x100 + (ch) *0x4)

#define MSGBOX_CHANNELS 2

// OpenCentauri: From sun8i platform.h
#define RTOS_MAGIC              "freertos"
#define MAGIC_SIZE              8
#define RTOS_VERSION            1
#define PADDING_LEN             (512)
#define DTS_SIZE                 (32)

/*the size is 48*/
typedef struct rtos_img_hdr_t {
    unsigned int  jump_instruction;   /* one intruction jumping to real code */
    unsigned char magic[MAGIC_SIZE];  /* ="freertos"*/
    unsigned int  check_sum;          /* generated by PC */
    unsigned int  image_size;         /* the size of image*/
    unsigned int  header_size;        /* the size of header */
    unsigned int  rtos_version;       /* rtos version */
    unsigned int  dram_size;          /* dram size in K*/
    unsigned int  rtos_run_addr;      /* rtos load addr*/
    unsigned int  dtb_addr;           /* dtb load addr*/
    unsigned int  dtb_size;           /* the size of dtb*/
    struct dts_msg_t dts_msg;
    unsigned char reserved[4];
} rtos_img_hdr;


typedef struct box_start_os_cfg {
    unsigned int used;
    unsigned int start_type;
    unsigned int irkey_used;
    unsigned int pmukey_used;
    unsigned int pmukey_num;
    unsigned int led_power;
    unsigned int led_state;
} box_start_os_cfg_t;

/*
typedef struct ir_code {
    unsigned int key_code;
    unsigned int addr_code;
} ir_code_t;

#define IR_NUM_KEY_SUP                  (64)
typedef struct ir_key {
    unsigned int num;
    ir_code_t ir_code_depot[IR_NUM_KEY_SUP];
} ir_key_t;
*/

struct dram_para_32 {
    /* normal configuration */
    unsigned int dram_clk;
    unsigned int dram_type;
    unsigned int dram_zq;
    unsigned int dram_odt_en;

    /* control configuration */
    unsigned int dram_para1;
    unsigned int dram_para2;

    /* timing configuration */
    unsigned int dram_mr0;
    unsigned int dram_mr1;
    unsigned int dram_mr2;
    unsigned int dram_mr3;
    unsigned int dram_tpr0;
    unsigned int dram_tpr1;
    unsigned int dram_tpr2;
    unsigned int dram_tpr3;
    unsigned int dram_tpr4;
    unsigned int dram_tpr5;
    unsigned int dram_tpr6;
    unsigned int dram_tpr7;
    unsigned int dram_tpr8;
    unsigned int dram_tpr9;
    unsigned int dram_tpr10;
    unsigned int dram_tpr11;
    unsigned int dram_tpr12;
    unsigned int dram_tpr13;
    unsigned int dram_tpr14;
    unsigned int dram_tpr15;
    unsigned int dram_tpr16;
    unsigned int dram_tpr17;
    unsigned int dram_tpr18;
    unsigned int dram_tpr19;
    unsigned int dram_tpr20;
    unsigned int dram_tpr21;
};
//typedef struct dram_para_32 __dram_para_t;

struct rtos_img_params_t {
    /* 32 * 4 = 128 byte */
    struct dram_para_32 dram_para;
    /* size ~ 56Bytes + 64Bytes*2 + 28Bytes = 212 Bytes */
    /* struct audio_param audio_param; */
    /* unsigned int message_pool_phys; */
    /* unsigned int message_pool_size; */
    /* unsigned int standby_base; */
    /* unsigned int standby_size; */
    /* unsigned int suart_status; */
    /* unsigned int pmu_bat_shutdown_ltf; */
    /* unsigned int pmu_bat_shutdown_htf; */
    /* unsigned int pmu_pwroff_vol; */
    /* unsigned int power_mode; */
    /* unsigned int power_start; */
    /* unsigned int powchk_used; */
    /* unsigned int power_reg; */
    /* unsigned int system_power; */
    /* 7 * 4 = 28 byte */
    struct box_start_os_cfg start_os;
    /* struct ir_key ir_key; */
    /* unsigned int reserved[256]; */
};

struct spare_rtos_head_t {
    struct rtos_img_hdr_t       rtos_img_hdr;
    struct rtos_img_params_t    rtos_img_params;
    unsigned char               padding[PADDING_LEN - sizeof(struct rtos_img_hdr_t) -
                                                      sizeof(struct rtos_img_params_t)];
    unsigned char               cert_magic[MAGIC_SIZE];
    unsigned int                cert_size;
    /* NOTICE: the 1k - 128 byete start version string */
};

// OpenCentauri: OEMHEAD stuff, used by msgbox
extern char *_oemhead_text_start;
#define platform_head ((struct spare_rtos_head_t *)&_oemhead_text_start)

extern uint32_t xtbsp_clock_freq_hz(void);
extern void dsp_msgbox_init(void (*rxcb)(uint32_t, uint32_t));
extern void dsp_msgbox_channel_send(uint32_t ch, uint8_t *bf, uint32_t len);

#endif
